---
platform: linux

image_resource:
  type: docker-image
  source: {repository: sconrod/netmiko}

inputs:
  - name: input
run:
  path: /bin/sh
  args:
    - -cex
    - |
      cd input
      /usr/local/bin/python -m pip install --upgrade pip
      chmod a+x configure_te_agent.sh
      ./configure_te_agent.sh



