---
platform: linux

image_resource:
  type: docker-image
  source: {repository: sconrod/netmiko}

inputs:
  - name: input
run:
  path: /bin/sh
  args:
    - -cex
    - |
      cd input
      chmod a+x scp.sh
      ./scp.sh
      chmod a+x configure_te_agents.sh
      ./configure_te_agents.sh
params:
  SSHKEY: ((ssh_aws_key))


